#!/bin/bash

#this script generates a random password for each user specified on the command line

#Display what the user typed on the command line.
echo "You executed this command: ${0}"
#0 means that positional parameter

#display the path and filename of the script
echo "You used $(dirname ${0}) as the path to the $(basename ${0}) script."

#Tell them how many arguments they passed in.
#(Inside the script they are parameters,outside they are arguments)
NUMBER_OF_PARAMETER="${#}"
echo "You supplied ${NUMBER_OF_PARAMETER} argument(s) on the command line."
#means that if you command ./luser-demo.sh hello world, then will add on 1 argument

#Makes sure that at least supply 1 argument statement.
if [[ "${NUMBER_OF_PARAMETER}" -lt 1 ]]
#-lt is less than ,can check by "man test"
then
  echo "Usage: ${0} USER_NAME [USER_NAME]..."
  exit 1
fi
#Generate and display a password for each parameter.
for USER_NAME in "${@}"
do
  PASSWORD=$(date +%s%N | sha256sum | head -c48)
  echo "${USER_NAME}: ${PASSWORD}"
done
